import logging
import pandas as pd
import numpy as np

logger = logging.getLogger(__name__)


class BudgetOptimizer:
    """
    Budget Optimizer

    Uses predicted revenue generated by the ML model
    to recommend future campaign budgets.

    This makes the optimizer usable on completely
    unseen datasets.
    """

    REQUIRED_COLUMNS = [
        "campaign_id",
        "campaign_name",
        "spend",
        "predicted_revenue",
        "conversion_rate"
    ]

    @staticmethod
    def safe_divide(a, b):
        b = b.replace(0, np.nan)
        return (a / b).fillna(0)

    def optimize(self, df: pd.DataFrame):

        logger.info("=" * 60)
        logger.info("Running Budget Optimizer...")
        logger.info("=" * 60)

        df = df.copy()

        ####################################################
        # Ensure required columns exist
        ####################################################

        for col in self.REQUIRED_COLUMNS:

            if col not in df.columns:

                logger.warning(f"{col} missing. Creating default values.")

                if col == "campaign_name":
                    df[col] = "Unknown"

                else:
                    df[col] = 0

        ####################################################
        # Predicted KPIs
        ####################################################

        df["predicted_roi"] = self.safe_divide(
            df["predicted_revenue"] - df["spend"],
            df["spend"]
        )

        df["predicted_roas"] = self.safe_divide(
            df["predicted_revenue"],
            df["spend"]
        )

        df["expected_profit"] = (
            df["predicted_revenue"] - df["spend"]
        )

        ####################################################
        # Recommendation Engine
        ####################################################

        recommendations = []

        for _, row in df.iterrows():

            roi = row["predicted_roi"]
            roas = row["predicted_roas"]
            conv = row["conversion_rate"]

            ################################################

            if roi >= 2:

                action = "Increase Budget"

                budget_change = 25

                priority = "High"

            elif roi >= 1:

                action = "Increase Budget"

                budget_change = 10

                priority = "Medium"

            elif roi >= 0.5:

                action = "Maintain Budget"

                budget_change = 0

                priority = "Low"

            elif roi >= 0:

                action = "Reduce Budget"

                budget_change = -20

                priority = "Low"

            else:

                action = "Pause Campaign"

                budget_change = -100

                priority = "Critical"

            ################################################

            confidence = round(

                (
                    min(max(roas, 0), 5) / 5 * 0.7
                    +
                    min(max(conv, 0), 1) * 0.3
                ) * 100,

                2

            )

            ################################################

            recommendations.append({

                "campaign_id": row["campaign_id"],

                "campaign_name": row["campaign_name"],

                "current_spend": round(
                    row["spend"],
                    2
                ),

                "predicted_revenue": round(
                    row["predicted_revenue"],
                    2
                ),

                "expected_profit": round(
                    row["expected_profit"],
                    2
                ),

                "predicted_roi": round(
                    roi,
                    2
                ),

                "predicted_roas": round(
                    roas,
                    2
                ),

                "conversion_rate": round(
                    row["conversion_rate"],
                    4
                ),

                "recommended_action": action,

                "recommended_budget_change_percent": budget_change,

                "recommended_budget": round(
                    row["spend"] * (1 + budget_change / 100),
                    2
                ),

                "priority": priority,

                "confidence_score": confidence

            })

        ####################################################

        recommendations = pd.DataFrame(recommendations)

        recommendations = recommendations.sort_values(

            by=[
                "predicted_roi",
                "expected_profit"
            ],

            ascending=False

        ).reset_index(drop=True)

        logger.info(
            f"Generated {len(recommendations)} budget recommendations."
        )

        logger.info("=" * 60)
        logger.info("Budget Optimization Complete.")
        logger.info("=" * 60)

        return recommendations