import { Bot, Sparkles } from "lucide-react";
import { GlassCard } from "@/components/ui/GlassCard";

type AISummaryCardProps = {
  summary: string;
};

export function AISummaryCard({ summary }: AISummaryCardProps) {
  return (
    <GlassCard className="relative overflow-hidden border-violet-500/20 p-5 sm:p-8">
      <div className="pointer-events-none absolute -right-10 -top-10 h-40 w-40 rounded-full bg-violet-500/15 blur-3xl" />
      <div className="pointer-events-none absolute -bottom-8 -left-8 h-32 w-32 rounded-full bg-indigo-500/10 blur-2xl" />

      <div className="relative">
        <div className="mb-6 flex items-center gap-3">
          <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-indigo-600 shadow-lg shadow-violet-500/25">
            <Bot className="h-5 w-5 text-white" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-semibold text-white">AI Summary</h2>
              <Sparkles className="h-4 w-4 text-violet-400" />
            </div>
            <p className="text-sm text-slate-400">Generated by MarketMind AI</p>
          </div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-[#0f0f14]/80 p-5 sm:p-6">
          <p className="text-base leading-relaxed text-slate-200 sm:text-lg">{summary}</p>
        </div>

        <p className="mt-4 text-xs text-slate-600">
          This summary synthesizes campaign performance, budget insights, and prediction data.
        </p>
      </div>
    </GlassCard>
  );
}
