import {
  Activity,
  ArrowDownRight,
  ArrowUpRight,
  Minus,
  Sparkles,
  TrendingDown,
  TrendingUp,
} from "lucide-react";
import { GlassCard } from "@/components/ui/GlassCard";
import type { ExecutiveSummary, TrendDirection } from "@/lib/insights-data";
import { cn } from "@/lib/utils";

type ExecutiveSummaryCardProps = {
  summary: ExecutiveSummary;
};

const healthStyles = {
  Strong: "text-emerald-400 bg-emerald-500/15 border-emerald-500/25",
  Moderate: "text-amber-400 bg-amber-500/15 border-amber-500/25",
  "At Risk": "text-rose-400 bg-rose-500/15 border-rose-500/25",
};

function TrendBadge({ value, direction }: { value: string; direction: TrendDirection }) {
  const Icon =
    direction === "up" ? ArrowUpRight : direction === "down" ? ArrowDownRight : Minus;

  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold",
        direction === "up" && "bg-emerald-500/15 text-emerald-400",
        direction === "down" && "bg-rose-500/15 text-rose-400",
        direction === "stable" && "bg-slate-500/15 text-slate-400",
      )}
    >
      <Icon className="h-3.5 w-3.5" />
      {value}
    </span>
  );
}

export function ExecutiveSummaryCard({ summary }: ExecutiveSummaryCardProps) {
  return (
    <GlassCard className="relative overflow-hidden border-indigo-500/20 p-5 sm:p-8">
      <div className="pointer-events-none absolute -right-16 -top-16 h-48 w-48 rounded-full bg-indigo-500/15 blur-3xl" />
      <div className="pointer-events-none absolute -bottom-12 -left-12 h-40 w-40 rounded-full bg-violet-500/10 blur-3xl" />

      <div className="relative">
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="flex items-start gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 shadow-lg shadow-indigo-500/30">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <div>
              <p className="text-xs font-medium uppercase tracking-wider text-indigo-300">
                Executive Summary
              </p>
              <h2 className="mt-1 text-xl font-semibold text-white sm:text-2xl">
                AI Business Report
              </h2>
              <p className="mt-1 text-sm text-slate-400">
                High-level performance overview generated by MarketMind AI
              </p>
            </div>
          </div>

          <div className="flex items-center gap-4">
            <div className="relative flex h-20 w-20 items-center justify-center">
              <div
                className="insights-score-ring absolute inset-0 rounded-full"
                style={{ ["--score" as string]: summary.overallScore }}
              />
              <div className="absolute inset-1.5 flex flex-col items-center justify-center rounded-full bg-[#0f0f14]">
                <span className="text-lg font-bold text-white">{summary.overallScore}</span>
                <span className="text-[10px] text-slate-500">Score</span>
              </div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
          <div className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
            <p className="text-xs text-slate-500">Overall Campaign Health</p>
            <span
              className={cn(
                "mt-2 inline-flex rounded-full border px-3 py-1 text-sm font-semibold",
                healthStyles[summary.overallCampaignHealth],
              )}
            >
              {summary.overallCampaignHealth}
            </span>
          </div>

          <div className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
            <p className="text-xs text-slate-500">Revenue Trend</p>
            <div className="mt-2 flex items-center gap-2">
              <TrendBadge
                value={summary.revenueTrend}
                direction={summary.revenueTrendDirection}
              />
              <TrendingUp className="h-4 w-4 text-emerald-400/60" />
            </div>
          </div>

          <div className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
            <p className="text-xs text-slate-500">Profit Trend</p>
            <div className="mt-2 flex items-center gap-2">
              <TrendBadge
                value={summary.profitTrend}
                direction={summary.profitTrendDirection}
              />
              <Activity className="h-4 w-4 text-indigo-400/60" />
            </div>
          </div>

          <div className="rounded-xl border border-emerald-500/15 bg-emerald-500/5 p-4 sm:col-span-1">
            <p className="text-xs text-slate-500">Best Performing Channel</p>
            <p className="mt-2 flex items-center gap-2 text-sm font-semibold text-emerald-300">
              <TrendingUp className="h-4 w-4 shrink-0" />
              {summary.bestPerformingChannel}
            </p>
          </div>

          <div className="rounded-xl border border-rose-500/15 bg-rose-500/5 p-4 sm:col-span-1">
            <p className="text-xs text-slate-500">Worst Performing Channel</p>
            <p className="mt-2 flex items-center gap-2 text-sm font-semibold text-rose-300">
              <TrendingDown className="h-4 w-4 shrink-0" />
              {summary.worstPerformingChannel}
            </p>
          </div>

          <div className="rounded-xl border border-indigo-500/20 bg-indigo-500/10 p-4 sm:col-span-2 xl:col-span-1">
            <p className="text-xs text-slate-500">Overall Score</p>
            <p className="mt-2 text-2xl font-bold text-white">{summary.overallScore}/100</p>
            <progress
              value={summary.overallScore}
              max={100}
              className="upload-progress mt-3 h-2 w-full"
            />
          </div>
        </div>
      </div>
    </GlassCard>
  );
}
